version: '3'

services:
  frontend:
    container_name: pers-frontend
    image: nginx
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      - "3000:80"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  backend:
    container_name: pers-backend
    build: backend
    ports:
      - 8080:8080
      - 7777:7777 #TODO Debug port
    depends_on:
      - database

    networks:
      - backend


  database:
    container_name: pers-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Person321
      MONGO_INITDB_DATABASE: person
    ports:
      - 27017:27017 # Remove in Prod
    networks:
      - backend
    volumes:
      - ./database/db-init.js:/docker-entrypoint-initdb.d/mongo-init.js

networks:
  backend:

