version: '3'

services:
  frontend:
    container_name: pers-frontend
    build: frontend
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
    ports:
      # TODO In order to run on prod, necessary due to server limitations. Port 80 and 8080 is allocated to the cinegame-backlog Project
      - 81:80
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80

  backend:
    container_name: pers-backend
    build: backend
    ports:
      - 8081:8080
      - 7777:7777 #Debug port

    depends_on:
      - database

    networks:
      - backend

  database:
    container_name: pers-db
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: Person321
      MONGO_INITDB_DATABASE: person
    ports:
      - 27017:27017 # Remove in Prod
    networks:
      - backend
    volumes:
      - ./database/db-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

networks:
  backend:

