###
POST http://localhost:8081/person/
Content-Type: application/json

{
  "id": null,
  "firstname": "Leo",
  "lastname": "Scherer",
  "email": "leo.scherer@bla.ch",
  "address": {
    "street": "Strasse",
    "number": "21",
    "zipcode": "6000",
    "city": "Luzern"
  },
  "phonenumber": "0790000000",
  "position": "CIO",
  "isAdmin": true,
  "username": "leo.scherer"
}

###

GET http://localhost:8081/person/609261ed8a2a0d70be755166



###
GET http://localhost:8081/person/query/firstname/leo
