###
POST http://localhost:8081/person/
Content-Type: application/json

{
  "id": null,
  "firstname": "Leo",
  "lastname": "Scherer",
  "email": "leo.scherer@bla.ch",
  "address": {
    "street": "Strasse",
    "number": "21",
    "zipcode": "6000",
    "city": "Luzern"
  },
  "phonenumber": "0790000000",
  "position": "CIO",
  "isAdmin": true,
  "username": "leo.scherer"
}

###

PUT http://localhost:8081/person/609b7390c2f5d658844a4421
Content-Type: application/json

{
  "firstname": "oooo",
  "lastname": "rrrr",
  "email": "leo.scherer@bla.ch",
  "address": {
    "street": "Strasse",
    "number": "21",
    "zipcode": "6000",
    "city": "jh"
  },
  "phonenumber": "fadsfdsf0xxxxxx",
  "position": "CIO",
  "isAdmin": true,
  "username": "leo.scherer"
}

###

GET http://localhost:8081/person/{{id}}



###
GET http://localhost:8081/person/query/firstname/{{firstname}}

###
DELETE http://localhost:8081/person/{{id}}

###
POST http://localhost:8081/auth/check-username

leo.scherer

###
POST http://localhost:8081/auth/register
Content-Type: application/json

{
  "username": "leo.scherer",
  "password": "blablabla"
}

###
POST http://localhost:8081/auth/verify-password
Content-Type: application/json

{
  "username": "leo.scherer",
  "password": "blablabla"
}

###
POST http://localhost:8081/auth/check-username

leo.scherer
