name: Continuous-Integration

on:
  push:
    branches:
      - master


jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout-Repository
        uses: actions/checkout@v2
        
      - name: Backend-build
        run: | 
          cd backend
          gradle build
          cd ..
  
  build-windows:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout-Repository
        uses: actions/checkout@v2
        
      - name: Backend-build
        run: | 
          cd backend
          gradle build
          cd ..
